#端口配置
server:
  port: 28070
  servlet:
    context-path: /sso
    session:
      timeout: 3600s
    jsp:
      init-parameters:
        development: true

spring:
  application:
    name: myshopping
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.mutil.userful.domain
  mapperLocations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml
  path: /home/logs/

